# Spring boot application
spring:
  application:
    name: dubbo-auto-configuration-provider-demo
# Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
dubbo:
  scan:
    base-packages: droid.user.service.impl
  # Dubbo Protocol
  protocol:
    name: dubbo
    port: 12345

  ## Dubbo Registry
  registry:
    address: N/A
